### ISSUE TITLE
Generic metrics

### ISSUE THREAD

**Issue by stevepeak** [asyncy/platform-engine#43]
Track the following metrics:

### Timers
1. `ms` to resolve data (or general python time)
1. `ms` to pull container (skip if no pull needed)
1. `ms` to run container (only one-off services, not streamers)
1. `ms` time in celery queue

### Gauges
1. `n` success vs failures per story
1. `n` success vs failures per container
1. `n` size of celery queues

### statsd
@joshpollara: I think we are using statsd for engine logs right? https://pypi.python.org/pypi/statsd

**Comment by stevepeak** [comment]
@joshpollara can you suggest some namespaces for these variables we would like to collect. 
Also, I believe some of these come out of the box with docker. Can we auto collect them into our Prometheus/grafana

**Comment by joshpollara** [comment]
OK so the new docker metrics endpoint is focused around Swarm. It shows metrics like cluster uptime, number of nodes in the cluster, CPUs, memory, IO usage, running containers, network usage. That kind of stuff. Def. related to the Swarm cluster and its health.

I think if we want to get metrics around docker pull times, success, failures, etc. we're going to have to keep track of that ourselves. Since we're initiating all of those commands though, I think this should be easy to keep track of and push into statsd. Does the engine already have an interface for keeping track of metrics? Something like dropwizard would be easy.

**Comment by stevepeak** [comment]
We do want to capture as many data points as possible, one of the benefits of Asyncy is metrics-out-of-the-box which can be used in a meaningful way, like application KPI's for example.

Let's get a this process started where a reasonable amount of metrics are collected by the Engine passed to Prometheus and exposed in Grafana dashboards.

> @joshpollara PS we no longer use Celery & RabbitMQ.

**Comment by joshpollara** [comment]
Spoke with @judepereira about this one. He's going to build out a prometheus exporter using the python client library.

https://github.com/prometheus/client_python

Then we can start on having default grafana dashboards

**Comment by judepereira** [comment]
To begin with, I'll have basic http-endpoint stats up and running.
